name: CI

on:
  push:
    branches:
     - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup dotnet v2.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.0.x' # SDK Version to use

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Pack
      run: dotnet pack "./${{ env.projectName }}/${{ env.projectName }}.csproj" -c Release

    - name: Push to nuget.org
      run: nuget push "./**/${{ env.projectName }}.*.nupkg" -ApiKey ${{ secrets.NUGET_APIKEY }} -source https://api.nuget.org/v3/index.json